consumes:
  - application/json

info:
  title: Consumer Mobile API v2 Service
  version: 1.46.0

definitions:
  ErrorResponse:
    properties:
      error_code:
        description: Machine-friendly error code
        type: string
      error_description:
        description: Human-friendly error code
        type: string
    required:
    - error_code
    type: object
    x-model: ErrorResponse

paths:
  /endpoint/v1:
    get:
      $ref: ./endpoint/v1/get.yaml#/get

produces:
  - application/json

swagger: '2.0'
